### PR TITLE
[Models] Llama2 fix

### PR DESCRIPTION
**Pull request by Aalanli**
Fix llama2 and add test for num_heads != num_key_value_heads.

### CODE REVIEW

**Comment by Aalanli** [comment]
This is quite strange, it seems that while the tests I added works on my local machine, it does not work on the CI server. I am investigating if the transformer versions are the same or not.

**Comment by yaoyaoding** [comment]
Have added a CI step to print out the version of installed python packages at #334 .

**Comment by Aalanli** [comment]
Right, it seems that the transformer version is 4.29.2, when the latest one is 4.31.0.

**Comment by yaoyaoding** [comment]
I see. The github ci will cache the python package (so that we do not need to reinstall the large packages like pytorch for every run), and this also makes some packages not up to date. 

Just cleared the python cache manually on the ci server.

**Comment by Aalanli** [comment]
It appears that updating transformers broke torch dynamo for bert, specifically for dynamic=True. This has nothing to do with our backend, though.

**Comment by yaoyaoding** [comment]
I see, could you skip the corresponding tests in this PR? Let's wait for the fix from pytorch people.

**Pull request merged**
