### PR TITLE
Sync CentML/hidet -> hidet-org/hidet

### PR DESCRIPTION
**Pull request by vadiklyutiy**
Sync CentML/hidet -> hidet-org/hidet

### CODE REVIEW

**Comment by yaoyaoding** [comment]
@vadiklyutiy I see you are in the author list of the 131 commits. This might because of the first two commits ("Sync" and "lint") that remove and add the EOF in the version file. Could you remove those two commits and try again?

**Comment by vadiklyutiy** [comment]
Could you clarify where did you look? 
I see in commit section the following 

image

So, some people authored, I'm commited

**Comment by yaoyaoding** [comment]
Interesting, here is what it looks like from my side: 

image

**Comment by vadiklyutiy** [comment]
@yaoyaoding please switch to Commit tab and take a look there

**Comment by vadiklyutiy** [comment]
On the conversation screen shows union of authors and committer. Because I am going to commit I added every wheere. But in history mainly authors does matter.

**Comment by vadiklyutiy** [comment]
in previous release #455 there were 98 commits. All of them I committed. 
But for example in contribution https://github.com/hidet-org/hidet/graphs/contributors I have 45 commit. Where I am a author are counted only

**Comment by yaoyaoding** [comment]
> On the conversation screen shows union of authors and committer. Because I am going to commit I added every wheere. But in history mainly authors does matter.

Yes, seems both the authors and commiters are merged in my view. Then it looks good to me. Previously I thought it might becuase of the first two commits, but it turned out it is not related. 

Then everything looks good to me, just kindly remind to bump the version after merge this pr and check the wheel submitted to pypi.

**Comment by vadiklyutiy** [comment]
> Then everything looks good to me, just kindly remind to bump the version after merge this pr and check the wheel submitted to pypi.

Pls formally approve this PR
I will change the version in the separate PR. Don't want to intermix it.

**Pull request merged**
