### PR TITLE
[Graph][Tensor] remove unnecessary synchronization

### PR DESCRIPTION
**Pull request by xiaocenxiaocen**

### CODE REVIEW

**Comment by yaoyaoding** [comment]
Hi @xiaocenxiaocen,

The link to default stream doc seems has broken, and the change does not pass our lint checking.

Hint: follow [here](https://docs.hidet.org/stable/developer-guides/contributing.html) to lint the code.

**Comment by xiaocenxiaocen** [comment]
> Hi @xiaocenxiaocen,
> 
> The link to default stream doc seems has broken, and the change does not pass our lint checking.
> 
> Hint: follow [here](https://docs.hidet.org/stable/developer-guides/contributing.html) to lint the code.

done

**Comment by yaoyaoding** [comment]
Hi @xiaocenxiaocen,

I still can not open this link: 
```
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html\?highlight\=default%20stream\#default-stream
```

There is an extra `\` after `index.html`.

**Comment by xiaocenxiaocen** [comment]
> Hi @xiaocenxiaocen,
> 
> I still can not open this link:
> 
> ```
> https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html\?highlight\=default%20stream\#default-stream
> ```
> 
> There is an extra `\` after `index.html`.

Sorry for the oversight. Now fixed.

**Comment by yaoyaoding** [comment]
Thanks @xiaocenxiaocen !

**Pull request merged**
