### PR TITLE
[SYNC] Sync CentML -> hidet-org

### PR DESCRIPTION
**Pull request by vadiklyutiy**
Regular sync CentML -> hidet-org

### CODE REVIEW

**Comment by vadiklyutiy** [comment]
yes, @c-fteixeira is looking into it

**Comment by yaoyaoding** [comment]
Kindly remind that we need to use "merge" instead of "squash and merge" in this PR.

**Comment by vadiklyutiy** [comment]
sure, I already asked Shang and he enabled merge and rebase option on this repo

**Comment by vadiklyutiy** [comment]
@yaoyaoding @wangshangsam @hjjq 
Tests passed.
Please look into and approve if everything is ok

**Review by yaoyaoding — APPROVED** [review]
LGTM, thanks @vadiklyutiy !

**Pull request merged**
